#! /bin/sh
# /etc/init.d/swapper
#

BASE_PATH = /home/prod/workspaces/github-parcelx/Swapper
MAIN_ENTRY = $BASE_PATH/main.go
MAIN_LOG = $BASE_PATH/main.log

case "$1" in
  start)
    nohup go run $MAIN_GO 2>&1 1>MAIN_LOG &
    echo "Swapper server #1 started"
    ;;
  stop)
     
    echo "Swapper server #1 stopped"
    ;;
  *)
    echo "Usage: /etc/init.d/swapper {start|stop}"
    exit 1
    ;;
esac

exit 0